pipeline {
    agent {
        label 'AGENT-1'
    }
    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        //retry(1)
    }
    environment {
        DEBUG = 'true'
        appVersion = '' // this will become global, we can use across pipeline
    }

     stages {
    stage('Read the version') {
      steps {
        dir('fundamentals/backend') {
          script {
            def pkg = readJSON file: 'package.json'
            echo "Version: ${pkg.version}"
          }
        }
      }
    }

    stage('Install Dependencies') {
      steps {
        dir('fundamentals/backend') {
          sh 'npm install'
        }
      }
    }

    stage('Docker build') {
      steps {
        dir('fundamentals/backend') {
          sh 'docker build -t myapp:${BUILD_NUMBER} .'
          sh 'docker images'
        }
      }
    }
  }

    post {
        always{
            echo "This sections runs always"
            deleteDir()
        }
        success{
            echo "This section run when pipeline success"
        }
        failure{
            echo "This section run when pipeline failure"
        }
    }
}