pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Hello, World!'
            }
        }
        stage('Test') {
            steps {
                echo 'This is the test stage.'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying application...'
            }
        }
    }
}